version: '1'
services:
  dawn:
    image: aron666/dawn
    container_name: dawn
    environment:
      - DW_USER=user
      - DW_PASS=password
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    volumes:
      - ./data:/app/data
    ports:
      - 5006:50006
    build: 
      context: .
      dockerfile: Dockerfile
